# Generated by Django 5.0.6 on 2024-07-09 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detaile_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Engine_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='search_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(null=True)),
                ('user', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='검색일시')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.TextField()),
                ('price', models.IntegerField(blank=True)),
                ('url', models.TextField()),
                ('detail_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='serch.detaile_name')),
                ('engine_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='serch.engine_name')),
                ('search_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
