# Generated by Django 5.0.6 on 2024-07-05 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='earch_data',
            new_name='search_data',
        ),
    ]
