# Generated by Django 5.0.6 on 2024-07-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serch', '0001_initial'),
    ]

    operations = [
    ]
