# Generated by Django 5.0.6 on 2024-07-09 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serch', '0002_auto_20240709_1314'),
    ]

    operations = [
    ]
