# Generated by Django 5.0.6 on 2024-07-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serch', '0002_rename_earch_data_search_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_data',
            name='content',
        ),
        migrations.AddField(
            model_name='search_data',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
