# Generated by Django 5.0.6 on 2024-07-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serch', '0005_alter_search_data_search_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_data',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
