# Generated by Django 5.0.6 on 2024-07-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serch', '0006_alter_search_data_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_data',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
