# Generated by Django 5.0.6 on 2024-07-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serch', '0007_alter_search_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_data',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
