# Generated by Django 5.0.6 on 2024-07-11 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serch', '0008_alter_search_data_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='search_data',
            unique_together={('user', 'title')},
        ),
    ]
