# Generated by Django 5.0.6 on 2024-07-11 02:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serch', '0010_search_keyword_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search_Keyword_Data',
            new_name='Search_Keyword_Record_Data',
        ),
    ]
