# Generated by Django 5.0.6 on 2024-07-11 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serch', '0011_rename_search_keyword_data_search_keyword_record_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='search_keyword_record_data',
            name='detail_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='serch.detaile_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search_keyword_record_data',
            name='engine_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='serch.engine_name'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='search_keyword_record_data',
            unique_together={('keyword', 'engine_name', 'detail_name', 'search_user')},
        ),
    ]
