# Generated by Django 5.0.6 on 2024-07-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serch', '0012_search_keyword_record_data_detail_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_keyword_record_data',
            name='count',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
