# Generated by Django 5.0.6 on 2024-07-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serch', '0013_alter_search_keyword_record_data_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_data',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
